version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-diary_backend_development}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-diary_backend_development}
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
      JWT_SECRET: ${JWT_SECRET:-development_jwt_secret}
      SEED_USER1_PASSWORD: ${SEED_USER1_PASSWORD:-secure_password_123}
      SEED_USER2_PASSWORD: ${SEED_USER2_PASSWORD:-secure_password_456}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    command: bundle exec rails server -b 0.0.0.0

volumes:
  postgres_data:
  redis_data:
  bundle_cache: 